@startuml C4_Elements
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
HIDE_STEREOTYPE()

Boundary(App, "Console Application", ".NET, C#, MySql"){
    
    Boundary(UI, "UI", ""){
        Container(Processor, "Processor", "", "Processes requests from user.") 
        Container(Layout, "Layout", "", "Handles layout design.")    
        Container(DataReader, "Data Reader", "", "Handles data reading.")
        Container(UIExceptions, "UIExceptions", "", "Holds custom exceptions for error handling.")

    }
    
    
    Boundary(Services, "Services",""){
        
        
        Container(Api, "API", "", "Orchestrates operations.")
        Container(Models, "Models", "", "Holds entities models.")
        Container(Enums, "Enumerators", "", "Holds enumarators.")
        Container(Repository, "Repository", "", "Handles entities logic, including read/write operations and cache.")
        Container(DataAccess, "DataAccess", "", "Handles database setting.")
        Container(HttpServices, "HttpServices", "", "Handles http requests.")
        Container(DataWriter, "DataWriter", "", "Handles output data writing operations.")
        Container(ServicesExceptions, "ServicesExceptions", "", "Holds custom exceptions for error handling.")
    
        ContainerDb(AppSettings, "AppSettings", "", "Holds appsettings.json values.")
    }

    ContainerDb(Database, "Database", "", "Stores entity data.")
}

System_Ext(OpenLibrary, "OpenLibrary API", "")
System_Ext(ExternalData, "Input data", "")

Rel(Processor, Layout, "")
Rel(Processor, UIExceptions, "")
Rel(DataReader, UIExceptions, "")
Rel(Processor, Api, "")
Rel(Processor, DataReader, "")
Rel(Api, HttpServices, "")
Rel(Api, DataWriter, "")
Rel(Api, Repository, "")
Rel(Api, Models, "")
Rel(Models, Enums, "")
Rel(Api, Enums, "")
Rel(Api, ServicesExceptions, "")
Rel(HttpServices, ServicesExceptions, "")
Rel(Repository, ServicesExceptions, "")
Rel(Repository, Enums, "")
Rel(Repository, Models, "")
Rel(DataWriter, Models, "")
Rel(DataWriter, AppSettings, "")
Rel(DataAccess, AppSettings, "")
Rel(HttpServices, AppSettings, "")
Rel(HttpServices, Models, "")
Rel(HttpServices, OpenLibrary, "")
Rel(Repository, DataAccess, "")
Rel(DataAccess, Database, "")
Rel(DataAccess, Models, "")
Rel(DataReader, ExternalData, "")

@enduml
